# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Audio_Text', models.TextField()),
                ('Audio_File', models.FileField(upload_to='')),
                ('Audio_Urdu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MCQ_Text', models.TextField(help_text='This is the MCQ')),
                ('Is_Correct', models.BooleanField(help_text='True if correct else false')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Ammount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('Expiry', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Text', models.TextField(help_text='This is the question')),
            ],
        ),
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField(default=0)),
                ('Passed', models.BooleanField(default=False)),
                ('Time_Stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Address', models.TextField()),
                ('DateRegistered', models.DateTimeField(auto_now_add=True)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('Lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='speak.Lesson')),
                ('Name', models.CharField(max_length=250)),
                ('Publication', models.DateTimeField(auto_now_add=True)),
                ('Required_Score', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='sitting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payments',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speak.UserInfo'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speak.Question'),
        ),
        migrations.AddField(
            model_name='audio',
            name='Lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speak.Lesson'),
        ),
        migrations.AddField(
            model_name='sitting',
            name='Test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speak.Testing'),
        ),
        migrations.AddField(
            model_name='question',
            name='Testing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speak.Testing'),
        ),
    ]
