# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0002_remove_payments_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='Expiry',
            field=models.DateTimeField(default=datetime.date(2017, 1, 19)),
            preserve_default=False,
        ),
    ]
