# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0003_payments_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Code',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
