# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0004_userinfo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='Audio_Urdu',
            field=models.TextField(max_length=1000),
        ),
    ]
